'use client';

import React, { useState } from 'react';
import Link from 'next/link';

// ============================================================================
// FULL MULTI-LANGUAGE DICTIONARY FOR THE ENTIRE MEMO BODY
// ============================================================================
const AUDIT_CONTENT = {
  en: {
    navTag: 'Localization Audit #04',
    title: 'Resend: Technical Intent & Regionalization Audit',
    subtitle: 'Deconstructing developer-marketing narratives for European B2B procurement standards.',
    readingTime: '8 min read',
    date: 'September 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs & Engineering Leads',
    s1Title: 'Section 1 / Perspective & Intent',
    overviewHeading: 'Context & Intent',
    overviewBody: 'In Silicon Valley, restraint is positioning. Conversational shorthand like "email" or "reach humans" signals simplicity and confidence. However, when developer infrastructure expands into LATAM and DACH markets, verbatim agency translations strip away that prestige—rendering high-margin developer tools as basic webmail clients or consumer marketing fluff.',
    overviewSub: 'This audit evaluates three critical touchpoints on Resend\'s primary acquisition layer, contrasting US baseline intent against traditional agency output and developer-native positioning.',
    s2Title: 'Section 2 / Core Acquisition Teardown',
    b1Title: '01 / The Hero Headline (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'In US tech culture, "email" is recognized shorthand for backend delivery infrastructure. Translated literally into European Spanish or German, "correo electrónico" shifts product categorization toward consumer webmail inbox clients like Outlook or Gmail. Inserting "API" restores category prestige while capturing high-volume regional search intent.',
    b2Title: '02 / The Core Value Proposition (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '"Reach humans" works in English because founder-led copy feels fresh here. Translated word-for-word, however, "llegar a humanos" sounds bizarre and unpolished to international B2B buyers. Engineering leads evaluate infrastructure on inbox placement, not vibes. Anchoring on deliverability metrics grounds the promise in parameters evaluators trust.',
    b3Title: '03 / The Primary Call to Action (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Passive verbs like "Empezar" or "Loslegen" carry zero technical momentum for engineering buyers. High-intent buyers don\'t want generic onboarding flows—they want immediate utility, such as generating an API key or running a payload test.',
    s3Title: 'Section 3 / Applied Surface Audits',
    s3Heading: '01 / React Email Integration',
    s3Body: 'Resend\'s native integration with React Email is its definitive technical moat. When localizing this documentation block, the messaging must preserve the gravity of component-driven architecture. Verbatim translation fails here because terms like "templating engine" carry different connotations across European enterprise developer tooling.',
    returnDir: '← Return to Directory',
    usBaseline: 'US Baseline',
    tradAgency: 'Traditional Agency Output',
    refinedIntent: 'Refined Technical Intent'
  },
  es: {
    navTag: 'Auditoría de Localización #04',
    title: 'Resend: Análisis de Intención Técnica y Regionalización',
    subtitle: 'Desmontando la narrativa para desarrolladores en entornos B2B europeos y de LATAM.',
    readingTime: '8 min de lectura',
    date: 'Septiembre 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs y Lideres de Ingeniería',
    s1Title: 'Sección 1 / Perspectiva e Intención',
    overviewHeading: 'Contexto y Objetivo',
    overviewBody: 'En Silicon Valley, la sobriedad es posicionamiento. El lenguaje informal como "email" o "llegar a humanos" transmite simplicidad y confianza. Sin embargo, cuando la infraestructura para desarrolladores se expande a LATAM y DACH, las traducciones literales eliminan ese prestigio, reduciendo herramientas técnicas de alto margen a simples clientes de correo web.',
    overviewSub: 'Esta auditoría evalúa tres puntos críticos en la capa de adquisición principal de Resend, contrastando la intención original de EE. UU. frente al resultado de agencias tradicionales y el posicionamiento técnico nativo.',
    s2Title: 'Sección 2 / Desglose Estructural de Adquisición',
    b1Title: '01 / El Titular Principal (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'En la cultura tech de EE. UU., "email" es una abreviación entendida para la infraestructura de entrega backend. Traducido literalmente como "correo electrónico", desplaza la categoría del producto hacia clientes webmail de consumo como Outlook o Gmail. Insertar "API" restaura el prestigio de la categoría mientras captura búsquedas regionales de alta intención.',
    b2Title: '02 / La Propuesta de Valor Central (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '"Reach humans" funciona en inglés porque el texto directo del fundador se siente fresco. Traducido palabra por palabra, "llegar a humanos" suena extraño eimpreciso para compradores B2B internacionales. Los líderes de ingeniería evalúan infraestructura por la entregabilidad en bandeja de entrada, no por sensaciones. Anclarse en métricas de entregabilidad fundamenta la promesa en parámetros técnicos reales.',
    b3Title: '03 / La Llamada a la Acción Principal (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Verbos pasivos como "Empezar" carecen de impulso técnico para un comprador de ingeniería. Los usuarios de alta intención no buscan un flujo de registro genérico; quieren utilidad inmediata, como generar una clave de API o ejecutar una prueba de payload.',
    s3Title: 'Sección 3 / Auditoría de Superficies Aplicadas',
    s3Heading: '01 / Integración con React Email',
    s3Body: 'La integración nativa de Resend con React Email es su ventaja técnica definitiva. Al localizar este bloque de documentación, el mensaje debe preservar el rigor de la arquitectura basada en componentes. La traducción literal falla aquí porque conceptos como "templating engine" tienen connotaciones muy distintas en el software empresarial europeo.',
    returnDir: '← Volver al Directorio',
    usBaseline: 'Línea Base (EE. UU.)',
    tradAgency: 'Resultado de Agencia Tradicional',
    refinedIntent: 'Intención Técnica Refinada'
  },
  de: {
    navTag: 'Lokalisierungs-Audit #04',
    title: 'Resend: Technische Intent-Analyse & Regionalisierung',
    subtitle: 'Dekonstruktion von Entwickler-Marketing-Narrativen für europäische B2B-Anforderungen.',
    readingTime: '8 Min. Lesezeit',
    date: 'September 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs & Lead Engineers',
    s1Title: 'Abschnitt 1 / Perspektive & Intent',
    overviewHeading: 'Kontext & Zielsetzung',
    overviewBody: 'Im Silicon Valley ist Zurückhaltung Positionierung. Informelle Begriffe wie „E-Mail“ oder „Menschen erreichen“ signalisieren Einfachheit. Bei der Expansion in den DACH-Raum nehmen wortwörtliche Agenturübersetzungen diesem B2B-Tool jedoch die technische Autorität und lassen es wie einen einfachen Webmail-Client wirken.',
    overviewSub: 'Dieses Audit analysiert drei kritische Touchpoints der primären Akquisitions-Ebene von Resend und stellt den US-Standard den typischen Agenturergebnissen sowie einer entwickler-nativen Positionierung gegenüber.',
    s2Title: 'Abschnitt 2 / Strukturelle Akquisitions-Analyse',
    b1Title: '01 / Die Hauptüberschrift (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'In der US-Tech-Kultur steht „E-Mail“ als Synonym für Backend-Zustellinfrastruktur. Wörtlich ins Deutsche übersetzt verschiebt „E-Mail“ die Produktkategorie in Richtung Consumer-Webmail. Das Einfügen von „API“ stellt das Kategorie-Prestige wieder her und deckt hochvolumigen regionalen Suchintent ab.',
    b2Title: '02 / Das zentrale Wertversprechen (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '„Reach humans“ funktioniert im US-Markt durch den nahbaren Gründer-Ton. Wortwörtlich übersetzt („Menschen erreichen“) wirkt es im europäischen B2B-Umfeld unpräzise. Engineering Leads bewerten Infrastruktur nach Posteingangszustellbarkeit, nicht nach Vibe. Die Verankerung auf Zustellbarkeits-Metriken schafft Vertrauen.',
    b3Title: '03 / Der primäre Call-to-Action (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Passive Verben wie „Loslegen“ bieten keinerlei technisches Momentum. High-Intent-Käufer suchen keine generischen Onboarding-Prozesse, sondern sofortige technische Verifizierung – etwa das Generieren eines API-Keys oder das Testen eines Payloads.',
    s3Title: 'Abschnitt 3 / Angewandte Oberflächen-Audits',
    s3Heading: '01 / React-Email-Integration',
    s3Body: 'Die native Integration von Resend mit React Email ist der entscheidende technische Wettbewerbsvorteil. Bei der Lokalisierung dieser Dokumentation muss die Architektursprache gewahrt bleiben. Wörtliche Übersetzungen scheitern an Begriffen wie „Templating Engine“, die im europäischen Enterprise-Umfeld abweichend konnotiert sind.',
    returnDir: '← Zurück zum Verzeichnis',
    usBaseline: 'US-Ausgangslage',
    tradAgency: 'Klassisches Agenturergebnis',
    refinedIntent: 'Präzisierter technischer Intent'
  },
  fr: {
    navTag: 'Audit de Localisation #04',
    title: 'Resend : Analyse d’Intention Technique et Régionalisation',
    subtitle: 'Déconstruction des récits dev-marketing pour les exigences B2B européennes.',
    readingTime: '8 min de lecture',
    date: 'Septembre 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs & Directeurs Ingenerie',
    s1Title: 'Section 1 / Perspective & Intention',
    overviewHeading: 'Contexte & Objectif',
    overviewBody: 'Dans la Silicon Valley, la sobriété sert de positionnement. Des expressions comme "email" ou "reach humans" traduisent la simplicité. Mais lors de l’expansion européenne, les traductions mot à mot des agences retirent ce prestige, réduisant un outil dev à un simple service de messagerie grand public.',
    overviewSub: 'Cet audit évalue trois points de conversion cruciaux sur la page principale de Resend, en opposant le texte US aux traductions d’agences et au positionnement technique natif.',
    s2Title: 'Section 2 / Déconstruction Structurelle de la Conversion',
    b1Title: '01 / Le Titre Principal (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'Dans la culture tech américaine, "email" désigne l’infrastructure de livraison backend. Traduit littéralement en français par "courrier électronique", le produit ressemble à un client webmail grand public. L’ajout du terme "API" restaure la valeur technique tout en ciblant les recherches régionales qualifiées.',
    b2Title: '02 / La Proposition de Valeur (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '"Reach humans" fonctionne en anglais car le style fondateur paraît authentique. Traduit mot à mot, "atteindre des humains" manque de rigueur pour les acheteurs B2B européens. Les responsables techniques évaluent l’infrastructure sur la délivrabilité en boîte de réception, pas sur l’émotion.',
    b3Title: '03 / L’Appel à l’Action Principal (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Des verbes passifs comme "Commencer" n’offrent aucun élan technique. Les profils à forte intention ne cherchent pas un parcours d’inscription générique : ils veulent générer une clé API ou tester une requête immédiatement.',
    s3Title: 'Section 3 / Audit des Surfaces Appliquées',
    s3Heading: '01 / Intégration React Email',
    s3Body: 'L’intégration native avec React Email constitue l’avantage concurrentiel majeur de Resend. La localisation de cette documentation doit préserver la rigueur de l’architecture orientée composants. La traduction littérale échoue ici car des termes comme "moteur de rendu" ont des connotations spécifiques dans l’IT européen.',
    returnDir: '← Retour au Répertoire',
    usBaseline: 'Référence US',
    tradAgency: 'Rendu Agence Traditionnelle',
    refinedIntent: 'Intention Technique Affinée'
  },
  it: {
    navTag: 'Audit di Localizzazione #04',
    title: 'Resend: Analisi dell’Intento Tecnico e Regionalizzazione',
    subtitle: 'Ristrutturazione delle narrative dev-marketing per i requisiti B2B europei.',
    readingTime: '8 min di lettura',
    date: 'Settembre 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs & Engineering Leads',
    s1Title: 'Sezione 1 / Prospettiva e Intento',
    overviewHeading: 'Contesto e Obiettivo',
    overviewBody: 'In Silicon Valley, la essenzialità è posizionamento. L’uso di termini colloquiali come "email" o "raggiungere persone" trasmette semplicità. Tuttavia, quando l’infrastruttura per sviluppatori si espande in Europa, le traduzioni letterali delle agenzie eliminano questo prestigio, riducendo strumenti ad alto margine a semplici client di posta.',
    overviewSub: 'Questo audit valuta tre punti critici sulla pagina d’acquisizione principale di Resend, mettendo a confronto il testo originale US con i risultati delle agenzie tradizionali e il posizionamento tecnico nativo.',
    s2Title: 'Section 2 / Analisi Strutturale della Conversione',
    b1Title: '01 / L’Titolo Principale (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'Nella cultura tech statunitense, "email" è l’abbreviazione riconosciuta per l’infrastruttura di consegna backend. Tradotto letteralmente come "posta elettronica", sposta la categoria del prodotto verso client di posta consumer come Outlook o Gmail. Inserire "API" ripristina il prestigio della categoria e intercetta le ricerche regionali ad alto valore.',
    b2Title: '02 / La Proposta di Valore Principale (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '"Reach humans" funziona in inglese grazie allo stile diretto dei fondatori. Tradotto parola per parola, "raggiungere umani" risulta bizzarro per i buyer B2B internazionali. I responsabili dell’ingegneria valutano l’infrastruttura sulla recapitabilità in inbox, non sulle sensazioni.',
    b3Title: '03 / La Call to Action Principale (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Verbi passivi come "Iniziare" non offrono alcun impulso tecnico per i buyer engineering. Gli utenti ad alto intento non cercano un flusso di registrazione generico, ma utilità immediata come generare una API key o testare una chiamata.',
    s3Title: 'Sezione 3 / Audit delle Superfici Applicate',
    s3Heading: '01 / Integrazione React Email',  pt: {
    navTag: 'Auditoria de Localização #04',
    title: 'Resend: Análise de Intenção Técnica e Regionalização',
    subtitle: 'Desconstruindo narrativas de dev-marketing para requisitos B2B europeus e LATAM.',
    readingTime: '8 min de leitura',
    date: 'Setembro 2026',
    client: 'Resend',
    markets: 'EU, LATAM, DACH',
    audience: 'CTOs e Líderes de Engenharia',
    s1Title: 'Seção 1 / Perspectiva e Intenção',
    overviewHeading: 'Contexto e Objetivo',
    overviewBody: 'No Vale do Silício, a sobriedade é posicionamiento. Termos informais como "email" ou "alcançar humanos" sinalizam simplicidade. Contudo, quando a infraestrutura para desenvolvedores se expande para LATAM e Europa, traduções literais de agências removem esse prestígio, transformando ferramentas técnicas em simples clientes de e-mail.',
    overviewSub: 'Esta auditoria avalia três pontos críticos na camada de aquisição da Resend, contrastando a intenção original dos EUA com o resultado de agências tradicionais e o posicionamento técnico nativo.',
    s2Title: 'Seção 2 / Desmontagem Estrutural de Aquisição',
    b1Title: '01 / O Título Principal (H1)',
    b1Baseline: '"Email for developers."',
    b1Agency: 'ES: Correo electrónico para desarrolladores.\nDE: E-Mail für Entwickler.',
    b1Refined: 'ES: La API de email para desarrolladores.\nDE: Die E-Mail-API für Entwickler.',
    b1Analysis: 'Na cultura tech dos EUA, "email" é um atalho reconhecido para infraestrutura de entrega backend. Traduzido literalmente como "correio eletrônico", desvia a categoria do produto para clientes webmail de consumo. Inserir "API" restaura o prestígio da categoria e captura buscas regionais de alta intenção.',
    b2Title: '02 / A Proposta de Valor Central (H2)',
    b2Baseline: '"The best API to reach humans instead of spam folders. Build, test, and deliver transactional emails at scale."',
    b2Agency: 'ES: La mejor API para llegar a humanos en lugar de carpetas de spam...\nDE: Die beste API, um Menschen statt Spam-Ordner zu erreichen...',
    b2Refined: 'ES: Máxima entregabilidad al inbox. Construye, prueba y envía correos transaccionales a escala.\nDE: Maximale Posteingangszustellbarkeit. Entwickeln, testen und versenden Sie transaktionale E-Mails im großen Stil.',
    b2Analysis: '"Reach humans" funciona em inglês porque o texto direto do fundador soa autêntico. Traduzido palavra por palavra, "alcançar humanos" soa estranho para compradores B2B internacionais. Líderes de engenharia avaliam infraestrutura pela entregabilidade na caixa de entrada, não por intuição.',
    b3Title: '03 / A Chamada para Ação Principal (CTA)',
    b3Baseline: '"Get Started"',
    b3Agency: 'ES: Empezar\nDE: Loslegen',
    b3Refined: 'ES: Probar API / Crear cuenta gratis\nDE: API testen / Kostenloses Konto erstellen',
    b3Analysis: 'Verbos passivos como "Começar" não possuem impulso técnico para compradores de engenharia. Usuários de alta intenção não querem fluxos genéricos de cadastro; buscam utilidade imediata, como gerar uma chave de API ou testar uma requisição.',
    s3Title: 'Seção 3 / Auditoria de Superfícies Aplicadas',
    s3Heading: '01 / Integração com React Email',
    s3Body: 'A integração nativa da Resend com React Email é sua vantagem técnica definitiva. Ao localizá-la, a mensagem deve preservar o rigor da arquitetura baseada em componentes. A tradução literal falha aqui porque termos como "engine de templates" possuem conotações distintas no mercado empresarial europeo.',
    returnDir: '← Voltar ao Diretório',
    usBaseline: 'Linha de Base (EUA)',
    tradAgency: 'Resultado de Agência Tradicional',
    refinedIntent: 'Intenção Técnica Refinada'
  }
};
